# Generated by Django 5.0.4 on 2024-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdcapp_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eduinstitution",
            name="region",
        ),
        migrations.AddField(
            model_name="eduinstitution",
            name="eduenv",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
