# Generated by Django 5.0.4 on 2024-04-29 21:34

import apps.rdcapp_api.common.validators.json_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdcapp_api", "0002_remove_eduinstitution_region_eduinstitution_eduenv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eduinstitution",
            name="eduenv",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[
                    apps.rdcapp_api.common.validators.json_validator.JSONSchemaValidator(
                        limit_value={
                            "oneOf": [
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "cdi": {
                                            "title": "Открыт ли в школе центр детских инициатив",
                                            "type": "boolean",
                                        },
                                        "cinema_club": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность киноклуба",
                                            "type": "integer",
                                        },
                                        "classes_are_eagles": {
                                            "title": 'Количество классов, реализующих программу "Орлята России"',
                                            "type": "integer",
                                        },
                                        "kdn": {
                                            "title": "Количество обучающихся, состоящих на каком-либо учете",
                                            "type": "integer",
                                        },
                                        "leaders_league": {
                                            "title": 'Участвуют ли старшеклассники в конкурсе "Лига вожатых"',
                                            "type": "boolean",
                                        },
                                        "leaders_squad": {
                                            "title": "Количество учащихся, вовлеченных в деятельность вожатского отряда",
                                            "type": "integer",
                                        },
                                        "mediacentre": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность медиацентра",
                                            "type": "integer",
                                        },
                                        "mpc": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность военно-патриотического клуба",
                                            "type": "integer",
                                        },
                                        "museum": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность музея",
                                            "type": "integer",
                                        },
                                        "rddm": {
                                            "pattern": "",
                                            "title": "Открыто ли в учреждении первичное отделение рддм",
                                            "type": "string",
                                        },
                                        "ssc": {
                                            "title": "Количество учащихся, вовлеченных в деятельность школьного спортивного клуба",
                                            "type": "integer",
                                        },
                                        "ssgo": {
                                            "title": "Действует ли в школе орган ученического самоуправления",
                                            "type": "boolean",
                                        },
                                        "theatre": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность театра",
                                            "type": "integer",
                                        },
                                        "tour_club": {
                                            "title": "Количество обучающихся, вовлеченных в деятельность туристического клуба",
                                            "type": "integer",
                                        },
                                        "uid": {
                                            "title": "Количество учащихся, вовлеченных в деятельность ЮИД",
                                            "type": "integer",
                                        },
                                        "volunteers_squad": {
                                            "title": "Количество учащихся, вовлеченных в деятельность волонтерского/добровольческого отряда",
                                            "type": "integer",
                                        },
                                        "y_rescuers_squad": {
                                            "title": "Количество учащихся, вовлеченных в деятельность отряда юных спасателей",
                                            "type": "integer",
                                        },
                                        "yunarmy_participants": {
                                            "title": "Количество зарегистрированных юнармейцев",
                                            "type": "integer",
                                        },
                                    },
                                    "type": "object",
                                },
                                {
                                    "additionalProperties": False,
                                    "properties": {
                                        "ccr": {
                                            "title": "Количество студентов, вовлеченных в деятельность КВН",
                                            "type": "integer",
                                        },
                                        "cinema_club": {
                                            "title": "Количество студентов, вовлеченных в деятельность киноклуба",
                                            "type": "integer",
                                        },
                                        "cyi": {
                                            "title": "Открыт ли в школе центр детских инициатив",
                                            "type": "boolean",
                                        },
                                        "kdn": {
                                            "title": "Количество обучающихся, состоящих на каком-либо учете",
                                            "type": "integer",
                                        },
                                        "leaders_league": {
                                            "title": 'Участвуют ли студенты в конкурсе "Лига вожатых"',
                                            "type": "boolean",
                                        },
                                        "leaders_squad": {
                                            "title": "Количество студентов, вовлеченных в деятельность вожатского отряда",
                                            "type": "integer",
                                        },
                                        "mediacentre": {
                                            "title": "Количество студентов, вовлеченных в деятельность медиацентра",
                                            "type": "integer",
                                        },
                                        "mpc": {
                                            "title": "Количество студентов, вовлеченных в деятельность военно-патриотического клуба",
                                            "type": "integer",
                                        },
                                        "museum": {
                                            "title": "Количество студентов, вовлеченных в деятельность музея",
                                            "type": "integer",
                                        },
                                        "rddm": {
                                            "title": "Открыто ли в учреждении первичное отделение рддм",
                                            "type": "boolean",
                                        },
                                        "ssc": {
                                            "title": "Количество студентов, вовлеченных в деятельность спортивного клуба",
                                            "type": "integer",
                                        },
                                        "ssgo": {
                                            "title": "Действует ли в учреждении орган студенческого самоуправления",
                                            "type": "boolean",
                                        },
                                        "theatre": {
                                            "title": "Количество студентов, вовлеченных в деятельность театра",
                                            "type": "integer",
                                        },
                                        "tour_club": {
                                            "title": "Количество студентов, вовлеченных в деятельность туристического клуба",
                                            "type": "integer",
                                        },
                                        "volunteers_squad": {
                                            "title": "Количество студентов, вовлеченных в деятельность волонтерского/добровольческого отряда",
                                            "type": "integer",
                                        },
                                    },
                                    "type": "object",
                                },
                            ],
                            "title": "Воспитательная среда",
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="EduSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edu_space_type",
                    models.CharField(
                        choices=[
                            ("museum__EduInstitutionType.SCHOOL", "Музей (Школа)"),
                            ("theatre__EduInstitutionType.SCHOOL", "Театр (Школа)"),
                        ]
                    ),
                ),
                ("edu_space", models.JSONField(blank=True, null=True)),
                (
                    "edu_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rdcapp_api.eduinstitution",
                    ),
                ),
            ],
        ),
    ]
