# Generated by Django 5.0.4 on 2024-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdcapp_api", "0003_alter_eduinstitution_eduenv_eduspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="avatar",
            field=models.ImageField(
                default="UserProfileDefaultIcon.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="eduspace",
            name="edu_space_type",
            field=models.CharField(
                choices=[
                    ("museum__EduInstitutionType.SCHOOL", "Музей (Школа)"),
                    ("theatre__EduInstitutionType.SCHOOL", "Театр (Школа)"),
                    ("theatre__EduInstitutionType.SPO", "Театр (СПО)"),
                ]
            ),
        ),
    ]
