# Generated by Django 5.0.4 on 2024-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rdcapp_api", "0004_employee_avatar_alter_eduspace_edu_space_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bio",
            field=models.CharField(blank=True, null=True),
        ),
    ]
