# Generated by Django 5.0.4 on 2024-05-03 10:46

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0005_employee_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eduinstitution',
            managers=[
                ('institutions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='UserProfileDefaultIcon.svg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_username',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='(?:@|(?:(?:(?:https?://)?t(?:elegram)?)\\.me\\/))(\\w{4,})$')]),
        ),
    ]
