# Generated by Django 5.0.4 on 2024-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0007_remove_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default='UserProfileDefaultIcon.svg', upload_to='avatars/'),
        ),
    ]
