# Generated by Django 5.0.4 on 2024-05-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0008_employee_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='snils',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='telegram_username',
        ),
    ]
