# Generated by Django 5.0.4 on 2024-05-03 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0009_remove_employee_phone_number_remove_employee_snils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='snils',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}-\\d{3}-\\d{3} \\d{2}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_username',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='(?:@|(?:(?:(?:https?://)?t(?:elegram)?)\\.me\\/))(\\w{4,})$')]),
        ),
    ]
