# Generated by Django 5.0.4 on 2024-05-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0010_employee_phone_number_employee_snils_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='quote',
        ),
    ]
