# Generated by Django 5.0.4 on 2024-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0011_remove_employee_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='quote',
            field=models.CharField(blank=True, null=True),
        ),
    ]
