# Generated by Django 5.0.4 on 2024-05-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0012_employee_quote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eduinstitution',
            managers=[
            ],
        ),
    ]
