# Generated by Django 5.0.4 on 2024-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0013_alter_eduinstitution_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='codegost',
            field=models.CharField(blank=True, null=True),
        ),
    ]
