# Generated by Django 5.0.1 on 2024-04-02 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('count_school', models.IntegerField(blank=True, null=True)),
                ('count_spo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('managment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.management')),
            ],
        ),
        migrations.CreateModel(
            name='EduInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adviser_post_introduced', models.BooleanField()),
                ('inn', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('kpp', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('title', models.CharField()),
                ('address', models.CharField(blank=True, null=True)),
                ('contingent', models.IntegerField(blank=True, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('priority', models.IntegerField(default=0)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('codegibdd', models.CharField()),
                ('codegost', models.CharField()),
                ('capital', models.CharField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('countschool', models.IntegerField(blank=True, null=True)),
                ('countspo', models.IntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.district')),
            ],
        ),
        migrations.CreateModel(
            name='Rc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, null=True)),
                ('baseorganization', models.CharField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.region')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.region'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField()),
                ('joindate', models.DateField(blank=True, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('tablenumber', models.CharField(db_column='TableNumber')),
                ('fireddate', models.DateField(blank=True, null=True)),
                ('login', models.CharField(default=models.CharField(db_column='TableNumber'))),
                ('firstname', models.CharField()),
                ('lastname', models.CharField()),
                ('patronymic', models.CharField(blank=True, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')])),
                ('telegram_username', models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='?:@|(?:(?:(?:https?://)?t(?:elegram)?)\\.me\\/))(\\w{4,})$')])),
                ('quote', models.CharField(blank=True, null=True)),
                ('edu_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.eduinstitution')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.post')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.region')),
            ],
        ),
        migrations.AddField(
            model_name='eduinstitution',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.region'),
        ),
    ]
