# Generated by Django 5.0.1 on 2024-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', null=True)),
                ('managmentid', models.IntegerField(blank=True, db_column='ManagmentID', null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eduinstitution',
            fields=[
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('typeid', models.IntegerField(db_column='TypeID')),
                ('signid', models.IntegerField(db_column='SignID')),
                ('municipalityid', models.UUIDField(db_column='MunicipalityID')),
                ('regionid', models.IntegerField(db_column='RegionID')),
                ('isadviserpostintroduced', models.BooleanField(db_column='IsAdviserPostIntroduced')),
                ('inn', models.TextField(db_column='INN')),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('contingent', models.IntegerField(blank=True, db_column='Contingent', null=True)),
            ],
            options={
                'db_table': 'EduInstitutionSpr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eduinstsign',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'EduInstSign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eduinsttype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'EduInstType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'Management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rc',
            fields=[
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('regionid', models.IntegerField(db_column='RegionID')),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('baseorganization', models.TextField(blank=True, db_column='BaseOrganization', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'RC',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='district',
            table='District',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='municipality',
            table='Municipality',
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
    ]
