# Generated by Django 5.0.1 on 2024-04-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0005_department_eduinstitution_eduinstsign_eduinsttype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Eduinstsign',
        ),
        migrations.DeleteModel(
            name='Eduinsttype',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eduinstitution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
