# Generated by Django 5.0.1 on 2024-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionID')),
            ],
            options={
                'db_table': 'MunicipalitySpr',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='region',
            table='RegionsSpr',
        ),
    ]
