# Generated by Django 5.0.1 on 2024-02-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0002_municipality_alter_region_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='DistrictSpr',
        ),
    ]
