# Generated by Django 5.0.1 on 2024-04-09 03:03

from django.db import migrations
from django.db import models, migrations
from django.apps import apps
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

def add_to_model(apps, schema_editor):
    '''
    Добавление данных в новую модель
    '''
    employee_model = apps.get_model("rdcapp_api", "Employee")
    user_model = apps.get_model("rdcapp_api", "User")
    result = employee_model.objects.create(
        field_1='Field_1 content',
        field_2='Field_2 content'
    )



class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0003_alter_subdivision_parent'),
    ]

    operations = [
    ]
