# Generated by Django 5.0.1 on 2024-02-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0003_alter_district_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(db_column='ID', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_column='Created')),
                ('joindate', models.DateField(db_column='JoinDate')),
                ('firstname', models.CharField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', null=True)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', null=True)),
                ('PostID', models.IntegerField(db_column='PostID')),
            ],
            options={
                'db_table': 'RegionsSpr',
                'managed': False,
            },
        ),
    ]
