version: '3.10'

services:
  django:
    build:
      context: .
      dockerfile: ./deploy/prod/django/Dockerfile
    env_file:
      - ./envs/prod/db.env
      - ./envs/prod/django.env
    volumes:
      - .:/app
      - /static:/static
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default_rdc_network
      
  db:
    image: postgres:16
    volumes:
      - ./dumps:/dumps
      - ./deploy/restore_db.sh:/restore_db.sh
      - pg_data:/var/lib/postgresql/pg_data
    env_file:
      - ./envs/prod/db.env
    networks:
      - default_rdc_network

volumes:
  pg_data:

networks:
 default_rdc_network:
