version: '3.10'

services:
  django:
    build:
      context: .
      dockerfile: ./deploy/local/django/Dockerfile
    env_file:
      - ./envs/local/db.env
      - ./envs/local/django.env
    volumes:
      - .:/app
      - static_files:/static
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - default_rdc_network
      
  db:
    image: postgres:16
    ports:
      - 5433:5432
    volumes:
      - ./dumps:/dumps
      - ./deploy/restore_db.sh:/restore_db.sh
      - pg_data:/var/lib/postgresql/pg_data
    env_file:
      - ./envs/local/db.env
    networks:
      - default_rdc_network

volumes:
  pg_data:
  static_files:

networks:
 default_rdc_network:
