# Generated by Django 5.0.1 on 2024-04-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.CreateModel(
            name='PostDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.department')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.post')),
            ],
        ),
    ]
