# Generated by Django 5.0.1 on 2024-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0002_remove_post_department_postdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
