# Generated by Django 5.0.1 on 2024-04-08 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0002_municipality_oktmo5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.subdivision'),
        ),
    ]
