# Generated by Django 5.0.1 on 2024-04-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdcapp_api', '0004_migrate_employee_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduInstitutionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.eduinstitution')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdcapp_api.employee')),
            ],
        ),
    ]
